batch_size: 16
device: !!python/object:pytorch_lightning.accelerators.cuda.CUDAAccelerator {}
hidden_fcn_dim: 32
hidden_gcn_dim: 32
learning_rate: 0.001
n_fcn_layers: 4
n_gcn_layers: 3
num_epochs: 500
seed: 2050
split: 0.3
