batch_size: 8
dec_hidden_dim_1: 256
dec_hidden_dim_2: 256
dropout: 0.2
enc_hidden_dim_1: 256
enc_hidden_dim_2: 256
height_dim: 41
input_dim: 2378
latent_dim: 32
learning_rate: 0.001
max_len: 58
num_epochs: 500
seed: 2050
split_ratio: 0.3
width_dim: 58
