batch_size: 16
device: !!python/object:pytorch_lightning.accelerators.cuda.CUDAAccelerator {}
hidden_fcn_dim: 32
hidden_gcn_dim: 64
learning_rate: 0.0001
n_fcn_layers: 1
n_gcn_layers: 3
num_epochs: 100
seed: 42
split: 0.3
