batch_size: 64
device: !!python/object:pytorch_lightning.accelerators.cuda.CUDAAccelerator {}
hidden_fcn_dim: 16
hidden_gcn_dim: 16
learning_rate: 0.0001
n_fcn_layers: 3
n_gcn_layers: 1
num_epochs: 300
seed: 104
split: 0.3
