batch_size: 32
device: !!python/object:pytorch_lightning.accelerators.cuda.CUDAAccelerator {}
hidden_fcn_dim: 16
hidden_gcn_dim: 32
learning_rate: 0.0001
n_fcn_layers: 2
n_gcn_layers: 2
num_epochs: 500
seed: 2050
split: 0.3
