batch_size: 16
device: !!python/object:pytorch_lightning.accelerators.cuda.CUDAAccelerator {}
hidden_fcn_dim: 64
hidden_gcn_dim: 16
learning_rate: 0.001
n_fcn_layers: 3
n_gcn_layers: 3
num_epochs: 500
seed: 1994
split: 0.3
