batch_size: 32
device: !!python/object:pytorch_lightning.accelerators.cuda.CUDAAccelerator {}
hidden_fcn_dim: 32
hidden_gcn_dim: 256
learning_rate: 0.0001
n_fcn_layers: 4
n_gcn_layers: 1
num_epochs: 500
seed: 500
split: 0.3
