batch_size: 64
device: !!python/object:pytorch_lightning.accelerators.cuda.CUDAAccelerator {}
hidden_fcn_dim: 32
hidden_gcn_dim: 32
learning_rate: 1.0e-05
n_fcn_layers: 2
n_gcn_layers: 1
num_epochs: 200
seed: 2050
split: 0.3
