batch_size: 32
device: !!python/object:pytorch_lightning.accelerators.cuda.CUDAAccelerator {}
hidden_fcn_dim: 32
hidden_gcn_dim: 128
learning_rate: 0.0001
n_fcn_layers: 2
n_gcn_layers: 3
num_epochs: 100
seed: 500
split: 0.3
