batch_size: 32
device: !!python/object:pytorch_lightning.accelerators.cuda.CUDAAccelerator {}
hidden_fcn_dim: 64
hidden_gcn_dim: 128
learning_rate: 1.0e-05
n_fcn_layers: 2
n_gcn_layers: 2
num_epochs: 300
seed: 42
split: 0.3
