batch_size: 64
device: !!python/object:pytorch_lightning.accelerators.cuda.CUDAAccelerator {}
hidden_fcn_dim: 32
hidden_gcn_dim: 128
learning_rate: 0.0001
n_fcn_layers: 5
n_gcn_layers: 1
num_epochs: 100
seed: 500
split: 0.3
