batch_size: 32
device: !!python/object:pytorch_lightning.accelerators.cpu.CPUAccelerator {}
hidden_fcn_dim: 16
hidden_gcn_dim: 128
learning_rate: 0.001
n_fcn_layers: 2
n_gcn_layers: 4
num_epochs: 100
seed: 1994
split: 0.3
