batch_size: 16
dec_hidden_dim_1: 256
dec_hidden_dim_2: 256
dropout: 0.4
enc_hidden_dim_1: 256
enc_hidden_dim_2: 256
height_dim: 41
input_dim: 2378
latent_dim: 32
learning_rate: 1.0e-05
max_len: 58
num_epochs: 250
seed: 1994
split_ratio: 0.3
width_dim: 58
