batch_size: 32
device: !!python/object:pytorch_lightning.accelerators.cuda.CUDAAccelerator {}
hidden_fcn_dim: 32
hidden_gcn_dim: 256
learning_rate: 0.0001
n_fcn_layers: 4
n_gcn_layers: 5
num_epochs: 1000
seed: 1994
split: 0.3
