batch_size: 32
device: !!python/object:pytorch_lightning.accelerators.cuda.CUDAAccelerator {}
hidden_fcn_dim: 128
hidden_gcn_dim: 128
learning_rate: 0.001
n_fcn_layers: 3
n_gcn_layers: 5
num_epochs: 1000
seed: 104
split: 0.3
